name: 'Version Visual Studio SDK projects'
description: 'Applies version information to Visual Studio SDK project files'
inputs:
  projectFilter: # id of input
    description: 'The wildcard filter that identifies projects to version'
    required: true
    default: '**/*.*proj'
  version:
    description: 'Maps to the Version element'
    required: false
  assemblyVersion:
    description: 'Maps to the AssemblyVersion element'
    required: false
  fileVersion:
    description: 'Maps to the FileVersion element'
    required: false
  informationalVersion:
    description: 'Maps to the InformationalVersion element'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: bookmark
  color: blue
