name: CI

on:
  push:
    branches:    
      - '**'
  pull_request:
    branches:    
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
      
    - name: Update project version
      uses: ./ # Uses an action in the root directory
      with:
        version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        assemblyVersion: ${{ steps.gitversion.outputs.assemblySemVer }}
        fileVersion: ${{ steps.gitversion.outputs.majorMinorPatch }}
        informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.

    - name: Pack
      run: |
        dotnet pack "./demo/csharp/csharp.csproj"
        dotnet pack "./demo/fsharp/fsharp.fsproj"
        dotnet pack "./demo/vbnet/vbnet.vbproj"
        find "${GITHUB_WORKSPACE}" -name *.nupkg

