name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch tags and master for GitVersion
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master
        
    - name: GitVersion
      id: gitversion
      uses: roryprimrose/rungitversion@v1.0.0

    - name: Update project version
      uses: ./ # Uses an action in the root directory
      with:
        version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
        assemblyVersion: ${{ steps.gitversion.outputs.AssemblySemVer }}
        fileVersion: ${{ steps.gitversion.outputs.MajorMinorPatch }}
       # informationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.

    - name: Pack
      run: |
        dotnet pack "./demo/csharp/csharp.csproj"
        dotnet pack "./demo/fsharp/fsharp.fsproj"
        dotnet pack "./demo/vbnet/vbnet.vbproj"
        find "${GITHUB_WORKSPACE}" -name *.nupkg

