name: CI

on:
  # Trigger the workflow on push or pull request,
  # for any branch or version tag
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore
      run: npm install
      
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.2
      
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info

  Acceptance_Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.8
      with:
          versionSpec: '5.x'
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: ./GitVersion.yml
      
    - name: Update project version
      uses: ./ # Uses an action in the root directory
      with:
        version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
        assemblyVersion: ${{ steps.gitversion.outputs.assemblySemVer }}
        fileVersion: ${{ steps.gitversion.outputs.majorMinorPatch }}
        informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.

    - name: Pack
      run: |
        dotnet pack "./demo/csharp/csharp.csproj"
        dotnet pack "./demo/fsharp/fsharp.fsproj"
        dotnet pack "./demo/vbnet/vbnet.vbproj"
        find "${GITHUB_WORKSPACE}" -name *.nupkg

